Add specification of device, manifests, tokens
FLECS-Technologies/flecs-console-api pull request #1
Opened 2024-02-14 12:42 UTC by alerei

2024-02-15 09:10 UTC, sulksamino requested changes

2024-02-15 09:10 UTC, sulksamino commented on api/v2/device/license/activate/openapi.json
> +    "description": "This is a sample description about this spec.",
Was the placeholder title and description intentional?

2024-02-15 09:10 UTC, sulksamino commented on api/v2/device/license/validate/openapi.json
> +    "description": "This is a sample description about this spec.",
Was the placeholder title and description intentional?

2024-02-15 09:10 UTC, sulksamino commented on api/v2/manifests/openapi.json
> +    "description": "This is a sample description about this spec.",
Was the placeholder title and description intentional?

2024-02-15 09:10 UTC, sulksamino commented on api/v2/tokens/openapi.json
> +    "description": "This is a sample description about this spec.",
Was the placeholder title and description intentional?

2024-02-15 09:10 UTC, sulksamino commented on api/v2/device/license/activate/openapi.json
> +                  },
```suggestion
                  }
```

2024-02-22 13:00 UTC, alerei commented on api/v2/device/license/activate/openapi.json
> +    "description": "This is a sample description about this spec.",
To be honest, the files are just a copy of what is already there. Don't think it's useful to fix these new files only, but to restructure the specification in general:

https://flecs-technologies.atlassian.net/browse/FLX-563

2024-02-22 15:58 UTC, merged